#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 14 09:03:13 2022

@author: machinex1
"""

import numpy as np
import pandas as pd
import cv2
import os
from matplotlib import pyplot as plt
from scipy.stats import skew

#Replace path with your folder name
path = "/Users/machinex1/Desktop/Flight 1 /Flight 2 - 25m 26102021"
dir_list = os.listdir(path)
dft_scores = []
dct_scores = []
j = 0
for i in dir_list:
    j = j+1
    file1 = path+'/'+i
    print(file1)
    img = cv2.imread(file1,0)
    dft = cv2.dft(np.float32(img),flags = cv2.DFT_COMPLEX_OUTPUT)
    dct = cv2.dct(np.float32(img))
    dft_shift = np.fft.fftshift(dft)
    dft = dft_shift.flatten()
    dct = dct.flatten()
    dft_list = dft.tolist()
    dct_list = dct.tolist()
    dft_df = pd.DataFrame(dft_list)
    dct_df = pd.DataFrame(dct_list)
    dft_df = dft_df.apply(lambda x: np.log(x))
    dct_df = dct_df.apply(lambda x: np.log(x))
    dft_df = dft_df.fillna(0)
    dct_df = dct_df.fillna(0)
    dft_df = np.where(dft_df > 1.0e-10, dft_df, 1.0e-10)
    dct_df = np.where(dct_df > 1.0e-10, dct_df, 1.0e-10)
    print(j)
    dft_scores.append(skew(dft_df))
    dct_scores.append(skew(dct_df))
dft_average = sum(dft_scores)/len(dft_scores)
dct_average = sum(dct_scores)/len(dct_scores)
print(path+ ' - DCT - ' + str(dct_average)+ ' - DFT - '+ str(dft_average))
fileout = open("/Users/machinex1/Desktop/Flight 1 /Dft_Dct_Scores","a")
fileout.write(path+ ' - DCT - ' + str(dct_average)+ ' - DFT - '+ str(dft_average)+"\n")
fileout.close()
